apps/task/urls.py
from django.urls import path

from . import views


app_name = 'task'


urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.detail, name='detail'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
]

apps/todolist/urls.py
from django.urls import path

from . import views


app_name = 'todolist'


urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.todolist, name='todolist'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [ 
    # Django admin
    path('admin/', admin.site.urls),
    
    # User management
    path('', include('accounts.urls')),
    
    
    path('', include('pages.urls')),
    path('', include('project.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/todolist/models.py
import uuid
from datetime import datetime, timezone
from django.db import models

from accounts.models import CustomUser
from project.models import Project


class TimeStampMixin(models.Model):
    created_at = models.DateTimeField(default=datetime.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Todolist(TimeStampMixin):    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, related_name='todolists', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    completion_date = models.DateField(null=True, blank=True)
    author = models.ForeignKey(CustomUser, related_name='todolists', on_delete=models.CASCADE)

    
    def mark_as_completed(self):
        self.is_completed = True
        self.completion_date = timezone.now().date()
        self.save()
        
    def __str__(self):
        return self.name

apps/todolist/forms.py
from django.forms import ModelForm
from .models import Todolist

class TodoListForm(ModelForm):
    class Meta:
        model = Todolist
        fields = ('name', 'description','is_completed')

apps/todolist/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from .models import Todolist
from project.models import Project
from .forms import TodoListForm
from django.utils import timezone

@login_required
def todolist(request, project_id, pk):
    project = Project.objects.filter(author=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=pk)

    return render(request, 'todolist/todolist.html', {
        'project': project,
        'todolist': todolist
    })


@login_required
def add(request, project_id):
    project = Project.objects.filter(author=request.user).get(pk=project_id)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if name:
            Todolist.objects.create(project=project, name=name, description=description, author=request.user)

            return redirect(f'/projects/{project_id}/')

    return render(request, 'todolist/add.html', {
        'project': project
    })


@login_required
# def edit(request, project_id, pk):
#     project = Project.objects.filter(author=request.user).get(pk=project_id)
#     todolist = Todolist.objects.filter(project=project).get(pk=pk)

#     if request.method == 'POST':
#         name = request.POST.get('name', '')
#         description = request.POST.get('description', '')

#         if name:
#             todolist.name = name
#             todolist.description = description
#             todolist.save()

#             return redirect(f'/projects/{project_id}/{pk}/')

#     return render(request, 'todolist/edit.html', {
#         'project': project,
#         'todolist': todolist
#     })
    

def edit(request,project_id,pk):
    project = Project.objects.filter(author=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=pk)
    instance = get_object_or_404(Todolist,pk=pk)
    if request.method == 'POST':
        form = TodoListForm(request.POST,instance=instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.completion_date = timezone.now().date()
            instance.save()
            print('Project created')
            return redirect(f'/projects/{project_id}/')
    else:
        form=TodoListForm(instance=instance)
    return render(request, 'project/edit.html', {'project': project,
        'todolist': todolist,'form': form})


@login_required
def delete(request, project_id, pk):
    project = Project.objects.filter(author=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=pk)
    todolist.delete()

    return redirect(f'/projects/{project_id}/')

templates/todolist/add.html
{% extends '_base.html' %}

{% block content %}
    <h1 class="ml-10 mt-10 mb-6 text-3xl">Add todolist</h1>
    <div class="flex items-center  w-full bg-teal-lighter justify-center">
        <div class="w-3/5 bg-white rounded shadow-lg p-8 m-4  ">
    <form class="mt-6 space-y-4" method="post" action=".">
        {% csrf_token %}
        <div class="flex flex-col mb-4">
            <label class="mb-2 uppercase font-bold text-lg text-grey-darkest" for="name">Name</label>
            <input class="border py-2 px-3 text-grey-darkest" type="text" name="name" id="name">
          </div>
          <div class="flex flex-col mb-4">
            <label class="mb-2 uppercase font-bold text-lg text-grey-darkest" for="description">Description</label>
            <textarea name="description" class="border w-full py-4 px-6 text-grey-darkest"></textarea>
          </div>
          <div>
            <button class="py-4 px-8 bg-blue-950 text-white rounded">Submit</button>
        </div>
    </form>
</div>
</div>
{% endblock %}

templates/todolist/edit.html
{% extends '_base.html' %}

{% block content %}
    <h1 class="ml-10 mt-10 mb-6 text-3xl">Edit todolist</h1>
    <div class="flex items-center  w-full bg-teal-lighter justify-center">
        <div class="w-3/5 bg-white rounded shadow-lg p-8 m-4  ">
    <form class="mt-6 space-y-4" method="post" action=".">
        {% csrf_token %}
        <div class="flex flex-col mb-4">
            <label class="mb-2 uppercase font-bold text-lg text-grey-darkest" for="name">Name</label>
            <input class="border py-2 px-3 text-grey-darkest" type="text" name="name" id="name" value="{{ todolist.name }}">
          </div>
          <div class="flex flex-col mb-4">
            <label class="mb-2 uppercase font-bold text-lg text-grey-darkest" for="description">Description</label>
            <textarea name="description" class="border w-full py-4 px-3 text-grey-darkest">{{ todolist.description }}</textarea>
          </div>
          <div class="flex flex-nowrap">
            <label class="mb-2 uppercase font-bold text-lg text-grey-darkest" for="is_completed">Completed</label>
            <input type="checkbox" class="ml-10 " id="is_completed" name="is_completed" />
          </div>
          <div>
            <button class="py-4 px-8 bg-blue-950 text-white rounded">Submit</button>
        </div>
    </form>
</div>
</div>
{% endblock %}

templates/todolist/todolist.html
{% extends '_base.html' %}

{% block content %}
<div class="ml-10 mt-10">
    <h1 class="mb-6 text-3xl">{{ todolist.name }}</h1>

    {% if todolist.description %}
        <p class="mb-6">{{ todolist.description }}</p>
    {% endif %}

    <a href="{% url 'task:add' project.id todolist.id %}" class="py-4 px-8 bg-blue-950 text-white inline-block rounded">Add task</a>
    <a href="{% url 'todolist:edit' project.id todolist.id %}" class="py-4 px-8 bg-sky-600 text-white inline-block rounded">Edit</a>
    <a href="{% url 'todolist:delete' project.id todolist.id %}" class="py-4 px-8 bg-red-600 font-bold text-white inline-block rounded">Delete</a>

    <div class="mt-6 grid grid-cols-4 gap-4">
        {% for task in todolist.tasks.all %}
            <div class="py-6 px-6 bg-slate-200">
                <a href="{% url 'task:detail' todolist.project.id todolist.id task.id %}">
                    <h2 class="mb-4 text-xl">{{ task.name }}</h2>

                    <p class="text-sm text-slate-600">
                        {{ task.description }}
                    </p>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}