apps/accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'


urlpatterns = [
    #path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path("logout", views.logout_request, name="logout"),
]

apps/project/urls.py
from django.urls import path

from . import views


app_name = 'project'


urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.add, name='add'),
    path('projects/', views.projects, name='projects'),
    path('<uuid:pk>/', views.project, name='project'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
    path('<uuid:project_id>/files/upload/', views.upload_file, name='upload_file'),
    path('<uuid:project_id>/files/<uuid:pk>/delete/', views.delete_file, name='delete_file'),
    path('<uuid:project_id>/notes/add/', views.add_note, name='add_note'),
    path('<uuid:project_id>/notes/<uuid:pk>/', views.note_detail, name='note_detail'),
    path('<uuid:project_id>/notes/<uuid:pk>/edit/', views.note_edit, name='note_edit'),
    path('<uuid:project_id>/notes/<uuid:pk>/delete/', views.note_delete, name='note_delete'),
    path('download-files/<uuid:parent_id>', views.download_files, name='download_all_files'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [ 
    # Django admin
    path('admin/', admin.site.urls),
    
    # User management
    path('', include('accounts.urls')),
    
    
    path('', include('pages.urls')),
    path('', include('project.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/_base.html
{% load static %}
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'src/styles.css' %}">
        <script src="https://cdn.tailwindcss.com"></script>
    </head>

    <body>
        <style>
            /* Media query for print */
            @media print {
                /* Hide the navigation bar using Tailwind utility classes */
                .print-hide {
                    display: none !important;
                }
                .print-button-hide {
                    display: none !important;
                }
            }
        </style>
        <nav class="py-6 px-8 flex items-center justify-between bg-blue-950 print-hide">
            <div class="text-2xl font-bold">
            <h1 class="text-xl text-white"><a href="{% url 'project:projects' %}">AcsServices Projects</a></h1>
            </div>
            <div class="space-x-4">
                {% if user.is_authenticated %}
                {% comment %} <button class="bg-rose-600 hover:bg-rose-700 text-white font-bold py-2 px-4 rounded mr-10"><a href="{% url 'project:projects' %}">Projects</a></button> {% endcomment %}
                <a href="#" class="text-white font-bold">{{user.username}}</a>
                <a href="{% url 'accounts:logout' %}" class="py-2 px-4 font-bold bg-yellow-300 hover:bg-yellow-400 text-blue-950 rounded mr-10">Log out</a>
                {% else %}
                <a href="{% url 'accounts:login' %}" class="py-2 px-4 font-bold bg-yellow-300 hover:bg-yellow-400 text-blue-950 rounded mr-10">Log in</a>
                {% endif %}
            </div>
        </nav>


{% block content %}
{% endblock %}
        <footer class="py-8 px-8 bg-blue-950 text-center">
            <p class="text-white">Copyright {% now "Y" %} - AcsServices</p>
        </footer>
    </body>
</html>

templates/home.html
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Home{% endblock %}

{% block content %}
        <main class="py-6 px-8">
            <header class="py-12 text-center bg-slate-200">
                <h1 class="text-3xl text-blue-950">Welcome to AcsServices</h1>
                {% if user.is_authenticated %}
                <button class="mt-6 w-96 bg-yellow-300 hover:bg-yellow-400 text-blue-950 font-bold py-2 px-4 rounded "><a href="{% url 'project:projects' %}">Projects</a></button>
                {% else %}
                <button class="mt-6 w-96 bg-yellow-300 hover:bg-yellow-400 text-blue-950 font-bold py-2 px-4 rounded "><a href="#">Projects</a></button>
                {% endif %}
            </header>
        </main>




{% endblock %}