apps/project/urls.py
from django.urls import path

from . import views


app_name = 'project'


urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.add, name='add'),
    path('projects/', views.projects, name='projects'),
    path('<uuid:pk>/', views.project, name='project'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
    path('<uuid:project_id>/files/upload/', views.upload_file, name='upload_file'),
    path('<uuid:project_id>/files/<uuid:pk>/delete/', views.delete_file, name='delete_file'),
    path('<uuid:project_id>/notes/add/', views.add_note, name='add_note'),
    path('<uuid:project_id>/notes/<uuid:pk>/', views.note_detail, name='note_detail'),
    path('<uuid:project_id>/notes/<uuid:pk>/edit/', views.note_edit, name='note_edit'),
    path('<uuid:project_id>/notes/<uuid:pk>/delete/', views.note_delete, name='note_delete'),
    path('download-files/<uuid:parent_id>', views.download_files, name='download_all_files'),
]

apps/todolist/urls.py
from django.urls import path

from . import views


app_name = 'todolist'


urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.todolist, name='todolist'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [ 
    # Django admin
    path('admin/', admin.site.urls),
    
    # User management
    path('', include('accounts.urls')),
    
    
    path('', include('pages.urls')),
    path('', include('project.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/project/models.py
import uuid,os
from datetime import datetime
from django.db import models
from accounts.models import CustomUser
from django.utils import timezone

class TimeStampMixin(models.Model):
    created_at = models.DateTimeField(default=datetime.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Project(TimeStampMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    completion_date = models.DateField(null=True, blank=True)
    author = models.ForeignKey(CustomUser, related_name='projects', on_delete=models.CASCADE)
    
    def mark_as_completed(self):
        self.is_completed = True
        self.completion_date = timezone.now().date()
        self.save()
    
    def delete(self, *args, **kwargs):
        # Deleting associated ChildModel objects
        files = self.files.all()
        for projectfile in files:
            projectfile.delete()
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.name

def custom_upload_path(instance, filename):
    # Get the related model's name and use it in the file path
    project = instance.project.name if instance.project else 'no_related_name'
    sanitized_model_name = project.replace(' ', '_').replace('-', '_').replace('|', '_')  # Add more replacements as needed
    
    # Use os.path.join for constructing the file path
    return os.path.join('custom_directory', sanitized_model_name, filename)
    #return f'custom_directory/{project}/{filename}'

class ProjectFile(TimeStampMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, related_name='files', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    attachment = models.FileField(upload_to=custom_upload_path)
    
    def delete(self, *args, **kwargs):
        # Delete the file when the object is deleted
        if self.attachment:
            if os.path.isfile(self.attachment.path):
                os.remove(self.attachment.path)
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.name



class ProjectNote(TimeStampMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, related_name='notes', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    body = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

apps/project/forms.py
from django.forms import ModelForm

from .models import ProjectFile, Project


class ProjectFileForm(ModelForm):
    class Meta:
        model = ProjectFile
        fields = ('name', 'attachment',)


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ('name', 'description','is_completed')

apps/project/views.py
from gzip import GzipFile
import zipfile
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from .forms import ProjectFileForm, ProjectForm
from .models import Project,ProjectNote
from django.shortcuts import render, redirect
from django.utils import timezone


@login_required
def home(request):
    return render(request, 'project/home.html')


@login_required
def projects(request):
    projects = Project.objects.filter(author=request.user)

    return render(request, 'project/projects.html', {
        'projects': projects
    })

@login_required
def project(request, pk):
    project = Project.objects.filter(author=request.user).get(pk=pk)

    return render(request, 'project/project.html', {
        'project': project
    })

# @login_required
# def add(request):
#   if request.method == 'POST':
#     name = request.POST.get('name', '')
#     description = request.POST.get('description', '')
    
#     if name:
#       Project.objects.create(name=name, description=description,author=request.user)

#       return redirect('/')
#     else:
#       print('Not valid')

#   return render(request, 'project/add.html')

@login_required
def add(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.author = request.user
            project.save()
            print('Project created')
            return redirect('/')
    else:
        form=ProjectForm()
    return render(request, 'project/add.html', {'form': form})
            



# @login_required
# def edit(request, pk):
#     project = Project.objects.filter(author=request.user).get(pk=pk)

#     if request.method == 'POST':
#         name = request.POST.get('name', '')
#         description = request.POST.get('description', '')

#         if name:
#             project.name = name
#             project.description = description
#             project.save()

#             return redirect('/')
    
#     return render(request, 'project/edit.html', {
#         'project': project
#     })


@login_required
def edit(request,pk):
    instance = get_object_or_404(Project,pk=pk)
    if request.method == 'POST':
        form = ProjectForm(request.POST,instance=instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.completion_date = timezone.now().date()
            instance.save()
            print('Project created')
            return redirect('/')
    else:
        form=ProjectForm(instance=instance)
    return render(request, 'project/edit.html', {'form': form})
    

@login_required
def delete(request, pk):
    project = Project.objects.filter(author=request.user).get(pk=pk)
    project.delete()

    return redirect('/projects/')



# Files


@login_required
def upload_file(request, project_id):
    project = Project.objects.filter(author=request.user).get(pk=project_id)

    if request.method == 'POST':
        form = ProjectFileForm(request.POST, request.FILES)

        if form.is_valid():
            projectfile = form.save(commit=False)
            projectfile.project = project
            projectfile.save()

            return redirect(f'/projects/{project_id}/')
    else:
        form = ProjectFileForm()

    return render(request, 'project/upload_file.html', {
        'project': project,
        'form': form
    })


@login_required
def delete_file(request, project_id, pk):
    project = Project.objects.filter(author=request.user).get(pk=project_id)
    projectfile = project.files.get(pk=pk)
    projectfile.delete()

    return redirect(f'/projects/{project_id}/')


# Notes


@login_required
def add_note(request, project_id):
    project = Project.objects.filter(author=request.user).get(pk=project_id)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        body = request.POST.get('body', '')

        if name and body:
            ProjectNote.objects.create(
                project=project,
                name=name,
                body=body
            )

            return redirect(f'/projects/{project_id}/')

    return render(request, 'project/add_note.html', {
        'project': project
    })


@login_required
def note_detail(request, project_id, pk):
    project = Project.objects.filter(author=request.user).get(pk=project_id)
    note = project.notes.get(pk=pk)

    return render(request, 'project/note_detail.html', {
        'project': project,
        'note': note
    })


@login_required
def note_edit(request, project_id, pk):
    project = Project.objects.filter(author=request.user).get(pk=project_id)
    note = project.notes.get(pk=pk)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        body = request.POST.get('body', '')

        if name and body:
            note.name = name
            note.body = body
            note.save()

            return redirect(f'/projects/{project_id}/')

    return render(request, 'project/note_edit.html', {
        'project': project,
        'note': note
    })


@login_required
def note_delete(request, project_id, pk):
    project = Project.objects.filter(author=request.user).get(pk=project_id)
    note = project.notes.get(pk=pk)
    note.delete()

    return redirect(f'/projects/{project_id}/')











from django.http import HttpResponse
from django.shortcuts import get_object_or_404
import os
from django.conf import settings

from .models import Project,ProjectFile

def download_files(request, parent_id):
    parent_model = get_object_or_404(Project, pk=parent_id)
    files = parent_model.files.all()  # Assuming related_name is not defined

    # Prepare zip file
    import zipfile
    from io import BytesIO

    zip_buffer = BytesIO()
    with zipfile.ZipFile(zip_buffer, 'a', zipfile.ZIP_DEFLATED, False) as zip_file:
        for attachment in files:
            file_path = os.path.join(settings.MEDIA_ROOT, str(attachment.attachment))
            folder_name, filename = os.path.split(file_path)
            zip_file.write(file_path, arcname=os.path.join(folder_name, f"{parent_model.name}_{filename}"))

    # Prepare response
    response = HttpResponse(zip_buffer.getvalue(), content_type='application/zip')
    response['Content-Disposition'] = f'attachment; filename={parent_model.name}_files.zip'
    response['Content-Length'] = zip_buffer.tell()
    return response

templates/project/add.html
{% extends '_base.html' %}

{% block content %}
    <h1 class="mt-10 text-center font-bold text-blue-950 mb-6 text-3xl">Add project</h1>
<div class="flex items-center  w-full bg-teal-lighter justify-center">
  <div class="w-3/5 bg-white rounded shadow-lg p-8 m-4  ">
    <form class="mt-6 space-y-4" method="post" action=".">
      {% csrf_token %}
        <div class="flex flex-col mb-4">
          <label class="mb-2 uppercase font-bold text-lg text-grey-darkest" for="name">Name</label>
          <input class="border py-2 px-3 text-grey-darkest" type="text" name="name" id="name">
        </div>
        <div class="flex flex-col mb-4">
          <label class="mb-2 uppercase font-bold text-lg text-grey-darkest" for="description">Description</label>
          <textarea name="description" class="border w-full py-4 px-6 text-grey-darkest"></textarea>
        </div>
        <div class="flex flex-nowrap">
          <label class="mb-2 uppercase font-bold text-lg text-grey-darkest" for="is_completed">Completed</label>
          <input type="checkbox" class="ml-10 " id="is_completed" name="is_completed" />
        </div>
        <div>
          <button class="py-4 px-8 bg-blue-950 text-white rounded">Submit</button>
        </div>
    </form>
  </div>
</div>
{% endblock %}

templates/project/add_note.html
{% extends '_base.html' %}

{% block content %}
    <h1 class="mt-10 ml-10 mb-4 text-3xl">Add note</h1>
    <div class="flex items-center  w-full bg-teal-lighter justify-center">
      <div class="w-3/5 bg-white rounded shadow-lg p-8 m-4  ">
    <form class="mt-6 space-y-4" method="post" action=".">
        {% csrf_token %}

        <div class="flex flex-col mb-4">
            <label class="mb-2 uppercase font-bold text-lg text-grey-darkest" for="name">Name</label>
            <input class="border py-2 px-3 text-grey-darkest" type="text" name="name" id="name">
          </div>

          <div class="flex flex-col mb-4">
            <label class="mb-2 uppercase font-bold text-lg text-grey-darkest" for="description">Body</label>
            <textarea name="description" class="border w-full py-4 px-6 text-grey-darkest"></textarea>
          </div>

        <div>
            <button class="py-4 px-8 bg-blue-950 text-white rounded">Submit</button>
        </div>
    </form>
    </div>
  </div>
{% endblock %}

templates/project/edit.html
{% extends '_base.html' %}

{% block content %}
    <h1 class="mt-10 ml-10 mb-6 text-3xl">Edit project</h1>
<div class="flex items-center  w-full bg-teal-lighter justify-center">
  <div class="w-3/5 bg-white rounded shadow-lg p-8 m-4  ">
    <form class="mt-6 space-y-4 " method="post" action=".">
      {% csrf_token %}
        <div class="flex flex-col mb-4">
          <label class="mb-2 uppercase font-bold text-lg text-grey-darkest" for="name">Name</label>
          <input class="border py-2 px-3 text-grey-darkest" type="text" name="name" id="name"  value="{{ form.instance.name }}">
        </div>
        <div class="flex flex-col mb-4">
          <label class="mb-2 uppercase font-bold text-lg text-grey-darkest" for="description">Description</label>
          <textarea name="description" class="border w-full py-4 px-6 text-grey-darkest">{{ form.instance.description }}</textarea>
        </div>
        <div class="flex flex-nowrap">
          <label class="mb-2 uppercase font-bold text-lg text-grey-darkest" for="is_completed">Completed</label>
          <input type="checkbox" class="ml-10 " id="is_completed" name="is_completed" {% if form.instance.is_completed %}checked{% endif %}/>
        </div>
        <div>
          <button class="py-4 px-8 bg-blue-950 text-white rounded">Submit</button>
        </div>
    </form>
  </div>
</div>
{% endblock %}

templates/project/edit_note.html
{% extends '_base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Edit note</h1>
    <div class="flex items-center  w-full bg-teal-lighter justify-center">
        <div class="w-3/5 bg-white rounded shadow-lg p-8 m-4  ">
    <form class="mt-6 space-y-4" method="post" action=".">
        {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input value="{{ note.name }}" name="name" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label>Body</label><br>
            <textarea name="body" class="w-full py-4 px-6 bg-slate-500 text-white" rows="20">{{ note.body }}</textarea>
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Save changes</button>
        </div>
    </form>
</div>
</div>
{% endblock %}

templates/project/note_detail.html
{% extends '_base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">{{ note.name }}</h1>

    <a href="{% url 'project:note_edit' project.id note.id %}" class="py-4 px-8 bg-sky-600 text-white inline-block">Edit</a>
    <a href="{% url 'project:note_delete' project.id note.id %}" class="py-4 px-8 bg-amber-600 text-white inline-block">Delete</a>

    <p class="mb-6">{{ note.body }}</p>
{% endblock %}

templates/project/project.html
{% extends '_base.html' %}

{% block content %}
    <h1 class="ml-10 mt-10 mb-6 text-3xl font-bold text-center text-blue-950 underline">{{ project.name }}</h1>

    {% if project.description %}
        <p class="ml-10 mb-6 font-bold text-lg text-center text-blue-950">{{ project.description }}</p>
    {% endif %}
    <div class="flex flex-wrap gap-1 ml-10">
    <a href="{% url 'todolist:add' project.id %}" class="py-4 px-8 bg-blue-950 text-white font-bold inline-block rounded print-button-hide">Add todolist</a>
    <a href="{% url 'project:edit' project.id %}" class="py-4 px-8 bg-sky-600 text-white font-bold inline-block rounded print-button-hide">Edit</a>
    <a href="{% url 'project:delete' project.id %}" class="py-4 px-8 bg-red-600 text-white font-bold inline-block rounded print-button-hide">Delete</a>
    <a href="javascript:void(0)" onclick="printPage()" class="py-4 px-8 bg-pink-600 text-white font-bold inline-block rounded print-button-hide">
      Print</a>
    </div>
    <h2 class="ml-10 mt-6 text-2xl">Todo lists</h2>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-2 ml-10 mr-10">
        {% for todolist in project.todolists.all %}
        {% if todolist.is_completed == True %}
            <div class="py-6 px-6 bg-green-400 rounded">
                {% else %}
            <div class="py-6 px-6 bg-slate-200 rounded">
                {% endif %}
                <p class="text-md text-slate-600">
                   Step {{ forloop.counter }}
                </p>
                <a href="{% url 'todolist:todolist' project.id todolist.id %}">
                    <h3 class="mb-4 text-2xl uppercase">{{ todolist.name }}</h3>

                    <p class="text-xl text-slate-600">
                        {{ todolist.description }}
                    </p>
                    <p class="text-sm text-slate-600">
                        {{ todolist.created_at }} from <a href="" class="font-medium"> {{ todolist.author }}</a>
                    </p>
                    <p class="text-sm text-slate-600">
                        {% if todolist.is_completed == True %}
                        Status: Completed at: {{ todolist.completion_date }}
                        {% elif todolist.is_completed == False %}
                        Status: In progress
                        {% elif todolist.is_completed == None %}
                        Status: -
                        {% endif %}
                        </p>
                </a>
            </div>
        {% endfor %}
    </div>

    <h2 class="ml-10 mt-6 text-2xl">Files</h2>

    <a href="{% url 'project:upload_file' project.id %}" class="ml-10 mt-6 py-4 px-8 bg-blue-950 text-white font-bold inline-block rounded print-button-hide">Upload file</a>
    <a href="{% url 'project:download_all_files' project.id %}" class="mt-6 py-4 px-8 bg-yellow-300 hover:bg-yellow-400 font-bold text-blue-950 inline-block rounded print-button-hide">Download files</a>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-6 gap-2 ml-10 mt-6 mr-10">
        {% for projectfile in project.files.all %}
            <div class="py-6 px-6 bg-slate-200 rounded">
                <h3 class="mb-4 text-xl">{{ projectfile.name }}</h3>

                <a href="{{ projectfile.attachment.url }}" target="_blank" class="text-sm text-slate-600">
                    Download file
                </a>

                |

                <a href="{% url 'project:delete_file' project.id projectfile.id %}" class="text-sm text-slate-600">
                    Delete
                </a>
                <p class="text-sm text-slate-600">
                    {{ projectfile.created_at }} from <a href="" class="font-medium"> {{ project.author }}</a>
                </p>
            </div>
        {% endfor %}
    </div>

    <h2 class="ml-10 mt-6 text-2xl">Notes</h2>

    <a href="{% url 'project:add_note' project.id %}" class="ml-10 mt-6 py-4 px-8 bg-blue-950 text-white font-bold inline-block rounded print-button-hide">Add note</a>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-2 ml-10 mt-6 mr-10 mb-6">
        {% for note in project.notes.all %}
            <div class="py-6 px-6 bg-slate-200 rounded">
                <a href="{% url 'project:note_detail' project.id note.id %}">
                    <h3 class="mb-4 text-xl">{{ note.name }}</h3>

                    <p class="text-sm text-slate-600">
                        {{ note.body|truncatechars:50 }}
                    </p>
                    <p class="text-sm text-slate-600">
                        {{ note.created_at }}
                    </p>
                </a>
            </div>
        {% endfor %}
    </div>
    <script>
        function printPage() {
            window.print();
        }
    </script>
{% endblock %}

templates/project/projects.html
{% extends '_base.html' %}
{% block content %}
    <h1 class="ml-10 mb-6 mt-10 text-3xl text-center text-blue-950 font-bold">Projects</h1>

    <a href="{% url 'project:add' %}" class="ml-10 py-4 px-8 bg-blue-950 text-white font-bold inline-block rounded">Add project</a>

    <div class="ml-10 mt-6 grid grid-cols-4 gap-4 mb-10">
        {% for project in projects %}
        {% if project.is_completed == True %}
            <div class="py-6 px-6 bg-green-400 rounded">
                {% else %}
                <div class="py-6 px-6 bg-slate-200 rounded">
                    {% endif %}
                <p class="text-md text-slate-600 text-center text-xl font-bold">
                    Project {{ forloop.counter }}
                 </p>
                <a href="{% url 'project:project' project.id %}">
                    <h2 class="mb-4 text-2xl">{{ project.name }}</h2>

                    <p class="text-xl text-slate-600">
                        {{ project.description }}
                    </p>
                </a></br>
                    <p class="text-sm text-slate-600">
                        {{ project.created_at }} from <a href="" class="font-medium"> {{ project.author }}</a>
                    </p>
                    <a href="{% url 'project:edit' project.id %}" class="text-green-700">Edit</a>
                    |
                    <a href="{% url 'project:delete' project.id %}" class="text-red-600">Delete</a>
                    <p class="text-sm text-slate-600">
                        {% if project.is_completed == True %}
                        Status: Completed at: {{ project.completion_date }}
                        {% elif project.is_completed == False %}
                        Status: In progress
                        {% elif project.is_completed == None %}
                        Status: -
                        {% endif %}
                        </p>
                    
                    </div>
        {% endfor %}
    </div>
{% endblock %}

templates/project/upload_file.html
{% extends '_base.html' %}

{% block content %}
    <h1 class="ml-10 mt-10 mb-6 text-3xl">Upload file to "{{ project.name }}"</h1>

    <form method="post" action="." enctype="multipart/form-data" class="ml-10">
        {% csrf_token %}
        <div class="flex items-center gap-x-4">
            <label for="Name">Name:</label>
            <input
              type="text"
              name="name"
              class="w-1/3 px-4 py-2 border border-gray-300 outline-none focus:border-gray-400"
              id="id_name"
            />
          </div>
          <label class="block">
            <span class="sr-only">Choose File</span>
            <input type="file" name="attachment"  id="id_attachment" class="mt-10 block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"/>
          </label>
        
        

        <div>
            <button class="mb-10 py-4 px-8 bg-blue-950 text-white mt-10 rounded">Submit</button>
        </div>
    </form>
{% endblock %}